Document: mirrorstage
Title: Debian mirrorstage Manual
Author: <insert document author here>
Abstract: This manual describes what mirrorstage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mirrorstage/mirrorstage.sgml.gz

Format: postscript
Files: /usr/share/doc/mirrorstage/mirrorstage.ps.gz

Format: text
Files: /usr/share/doc/mirrorstage/mirrorstage.text.gz

Format: HTML
Index: /usr/share/doc/mirrorstage/html/index.html
Files: /usr/share/doc/mirrorstage/html/*.html
